### ISSUE TITLE
How to correctly install dep as gem?

### ISSUE THREAD

**Issue by ce-manalang** [cyx/dep#7]
Hi all,

I installed dep using `gem install dep`.

Machine setup is as follows:

```
PATH = $HOME/.rubies/2.0.0-p0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
GEM_HOME = $HOME/.rubies/2.0.0-p0/lib/ruby/gems/2.0.0
GEM_PATH = $HOME/.gem/ruby/2.0.0:$HOME/.rubies/2.0.0-p0/lib/ruby/gems/2.0.0
```

`which dep` returns `$HOME/.rubies/2.0.0-p0/bin/dep`

dep is installed in `$HOME/.rubies/2.0.0-p0/lib/ruby/gems/2.0.0/gems/dep-1.0.5/bin/dep`

When I run `dep` it returns nothing

I'm thinking it's because of the if condition in line: 149 `if __FILE__ == $0`
It returns false because `__FILE__ = $HOME/.rubies/2.0.0-p0/lib/ruby/gems/2.0.0/gems/dep-1.0.5/bin/dep` and `$0 = $HOME/.rubies/2.0.0-p0/bin/dep`

Did I do something wrong with the installation? What do you guys think?

Thanks in advance!!!

**Comment by ericgj** [comment]
I had the same problem, see pull request #8

**Comment by djanowski** [comment]
Same error here. Dep doesn't work via RubyGems. @cyx?

**Comment by cyx** [comment]
Checking!

**Comment by cyx** [comment]
I've released 1.0.6 which should fix this bug.

**Comment by djanowski** [comment]
cc @kevinjhanna

**Comment by kevinjhanna** [comment]
:+1:

**Comment by ce-manalang** [comment]
works now. thanks. closing ticket.
